- name: create directories
  file:
    path: '{{item}}'
    state: directory
  with_items: '{{hdfs_dfs_datanode_data_dir}}'


#- name: start datanodes
#  command:
#    cmd: '{{hdfs_hadoop_home}}/bin/hdfs --daemon start datanode'