- name: add ssh public keys to authroized_keys
  lineinfile:
    line: "{{item}}"
    dest: "~/.ssh/authorized_keys"
    state: present
    create: yes
  with_items: "{{ssh_public_keys}}"


- name: install install some initial packages on debian systems
  apt:
    update_cache: yes
    name:
      - zsh
      - git
      - byobu
      - vim
      - curl
    state: present
  when: ansible_facts['os_family']|lower == 'debian'


- name: install some initial packages on rhel systems
  yum:
    update_cache: yes
    name:
      - *
      - zsh
      - git
      - epel-release
      - byobu
      - vim
      - curl
    state: latest
  when: ansible_facts['os_family']|lower == 'redhat'


- name: install oh-my-zsh
  shell:
    cmd: 'yes | sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"'


- name: change zsh theme
  lineinfile:
    dest: "~/.zshrc"
    regexp: "^ZSH_THEME=.+"
    line: 'ZSH_THEME="aussiegeek"'
    state: present


- name: change default shell to zsh
  user:
    name: root
    shell: /usr/bin/zsh


#- name: enable byobu
#  command: "byobu-enable && exit`"
