version: '3.7'
services:
  pinot-server:
    image: dockerhub.ir/apachepinot/pinot:0.9.2
    command: "StartServer -serverHost 172.30.125.53 -zkAddress  172.30.125.45:2181,172.30.125.46:2181,172.30.125.47:2181 -clusterName PinotCluster -configFileName /opt/pinot/conf/server.conf"
    restart: unless-stopped
    container_name: "manual-pinot-server" 
    volumes:
      - dataDir:/tmp/dataDir
      - segmentTarDir:/tmp/segmentTarDir
      - ./server.conf:/opt/pinot/conf/server.conf
      - /opt/hadoop:/opt/hadoop
    extra_hosts:
      - "rm-bd-kafka-01.bigdata.digikala.com:172.30.125.27" 
      - "rm-bd-kafka-02.bigdata.digikala.com:172.30.125.28" 
      - "rm-bd-kafka-03.bigdata.digikala.com:172.30.125.29" 
      - "rm-bd-kafka-04.bigdata.digikala.com:172.30.125.30" 
      - "rm-bd-kafka-05.bigdata.digikala.com:172.30.125.31" 
      - "rm-bd-kafka-06.bigdata.digikala.com:172.30.125.32" 
      - "rm-bd-kafka-07.bigdata.digikala.com:172.30.125.33" 
    network_mode: host
    environment:
      JAVA_OPTS: "-Dplugins.dir=/opt/pinot/plugins -Xms4G -Xmx52G -XX:+UseG1GC -XX:MaxGCPauseMillis=200 -Xloggc:gc-pinot-server.log -javaagent:/opt/pinot/etc/jmx_prometheus_javaagent/jmx_prometheus_javaagent-0.12.0.jar=8888:/opt/pinot/etc/jmx_prometheus_javaagent/configs/pinot.yml"
      CLASSPATH_PREFIX: "${HADOOP_HOME}/share/hadoop/hdfs/hadoop-hdfs-client-${HADOOP_VERSION}.jar:${HADOOP_HOME}/share/hadoop/hdfs/hadoop-hdfs-native-client-${HADOOP_VERSION}.jar:${HADOOP_HOME}/share/hadoop/hdfs/hadoop-hdfs-${HADOOP_VERSION}.jar:${HADOOP_HOME}/share/hadoop/common/lib/hadoop-annotations-${HADOOP_VERSION}.jar:${HADOOP_HOME}/share/hadoop/common/lib/hadoop-auth-${HADOOP_VERSION}.jar:${HADOOP_HOME}/share/hadoop/common/hadoop-common-${HADOOP_VERSION}.jar:${HADOOP_HOME}/share/hadoop/common/lib/guava-${HADOOP_GUAVA_VERSION}.jar:${HADOOP_HOME}/share/hadoop/common/lib/gson-${HADOOP_GSON_VERSION}.jar:${HADOOP_HOME}/share/hadoop/common/lib/commons-configuration2-2.1.1.jar:${HADOOP_HOME}/share/hadoop/common/lib/htrace-core4-4.1.0-incubating.jar"
  
volumes:
  dataDir:
  segmentTarDir:
