- name: install redis on debian systems
  import_tasks: debian.yml
  when: ansible_facts['os_family']|lower == 'debian'


- name: install redis on rhel systems
  import_tasks: rhel.yml
  when: ansible_facts['os_family']|lower == 'redhat'