- name: create directories
  file:
    path: '{{item}}'
    state: directory
  with_items: '{{hdfs_dfs_namenode_name_dir}}'


#- name: start active namenode
#  command:
#    cmd: '{{hdfs_hadoop_home}}/bin/hdfs --daemon start namenode'
#  when: "'activenamenodeserver' in group_names"


- name: start cluster
  command:
    cmd: '{{hdfs_hadoop_home}}/sbin/start-dfs.sh'
  when: "'activenamenodeserver' in group_names"


- name: format filesystem
  command:
    cmd: '{{hdfs_hadoop_home}}/bin/hdfs namenode -format'
  when: "'activenamenodeserver' in group_names"


- name: format zkfc in namenodes
  command:
    cmd: '{{hdfs_hadoop_home}}/bin/hdfs zkfc -formatZK'


- name: stop cluster
  command:
    cmd: '{{hdfs_hadoop_home}}/sbin/stop-dfs.sh'
  when: "'activenamenodeserver' in group_names"


- name: start cluster
  command:
    cmd: '{{hdfs_hadoop_home}}/sbin/start-dfs.sh'
  when: "'activenamenodeserver' in group_names"


- name: copy meta data to standby namenodes
  command:
    cmd: '{{hdfs_hadoop_home}}/bin/hdfs namenode -bootstrapStandby'
  when: "'standbynamenodeservers' in group_names"


- name: start standby namenodes
  command:
    cmd: '{{hdfs_hadoop_home}}/bin/hdfs --daemon start namenode'
  when: "'standbynamenodeservers' in group_names"


#- name: start zkfc in namenodes
#  command:
#    cmd: '{{hdfs_hadoop_home}}/bin/hdfs --daemon start zkfc'
