- name: create directories
  file:
    path: '{{item}}'
    state: directory
  with_items: '{{hdfs_dfs_namenode_name_dir}}'


- name: copy namenode public key to datanodes
  local_action: "shell ssh root@{{ansible_default_ipv4.address}} 'cat ~/.ssh/id_rsa.pub' | ssh root@{{item}}  'cat >> ~/.ssh/authorized_keys'"
  with_items: "{{groups['datanodeservers']}}"


- name: format filesystem
  shell:
    cmd: 'yes | {{hdfs_hadoop_home}}/bin/hdfs namenode -format -force'
  when: "'activenamenodeserver' in group_names"


- name: format zkfc in namenodes
  shell:
    cmd: 'yes | {{hdfs_hadoop_home}}/bin/hdfs zkfc -formatZK -force'
  ignore_errors: yes


- name: start cluster
  command:
    cmd: '{{hdfs_hadoop_home}}/sbin/start-dfs.sh'
  when: "'activenamenodeserver' in group_names"


- name: copy meta data to standby namenodes
  shell:
    cmd: 'yes | {{hdfs_hadoop_home}}/bin/hdfs namenode -bootstrapStandby -force'
  when: "'standbynamenodeservers' in group_names"


- name: stop cluster
  command:
    cmd: '{{hdfs_hadoop_home}}/sbin/stop-dfs.sh'
  when: "'activenamenodeserver' in group_names"


- name: start cluster
  command:
    cmd: '{{hdfs_hadoop_home}}/sbin/start-dfs.sh'
  when: "'activenamenodeserver' in group_names"
