---
roles:
  - name: geerlingguy.firewall


  - name: geerlingguy.php
    version: 4.3.1

  - src: https://github.com/geerlingguy/ansible-role-passenger
    name: passenger
    version: 2.0.0

  - src: https://www.example.com/ansible/roles/my-role-name.tar.gz
    name: my-role
