# installation vars


hdfs_unarchived_filename: "hadoop-3.3.0"
hdfs_download_link: "https://downloads.apache.org/hadoop/common/stable/{{hdfs_unarchived_filename}}.tar.gz"
hdfs_download_sha_sum: "9ac5a5a8d29de4d2edfb5e554c178b04863375c5644d6fea1f6464ab4a7e22a50a6c43253ea348edbd114fc534dcde5bdd2826007e24b2a6b0ce0d704c5b4f5b"
hdfs_download_destination: "/opt/{{hdfs_unarchived_filename}}.tar.gz"
hdfs_unarchive_destination: "/opt/"


# core-site.xml

hdfs_fs_defaultFS: "ha-cluster"
hdfs_trash_interval: 1440
hdfs_dfs_journalnode_edits_dir: "/root/HA/data/jn"
hdfs_ha_zookeeper_quorum:
  - "172.16.4.100:2181"
  - "172.16.4.102:2181"
  - "172.16.4.104:2181"


# hadoop-env.sh

hdfs_namenode_user: root
hdfs_datanode_user: root
hdfs_secondarynamenode_user: root
hdfs_journalnode_user: root
hdfs_zkfc_user: root
hdfs_java_home: /usr
hdfs_hadoop_home: /opt/hadoop
hdfs_hadoop_conf_dir: /opt/hadoop/etc/hadoop
hdfs_hadoop_daemon_root_logger: WARN,RFA
hdfs_hadoop_heapsize_max: ''
hdfs_hadoop_heapsize_min: ''
hdfs_hadoop_jaas_debug: ''
hdfs_hadoop_workers: ''
hdfs_hadoop_log_dir: ''
hdfs_hadoop_pid_dir: ''
hdfs_hadoop_niceness: ''


# hdfs-site.xml

hdfs_dfs_replication: 1
hdfs_dfs_namenode_name_dir:
  - /root/hadoop-name-1
  - /root/hadoop-name-2
hdfs_dfs_nameservices: "ha-cluster"
hdfs_dfs_datanode_data_dir:
  - /root/hadoop-data-1
  - /root/hadoop-data-2
hdfs_ha_automatic_failover_enabled: "true"
hdfs_dfs_ha_fencing_methods: "sshfence"
hdfs_dfs_ha_fencing_ssh_private_key_files: /root/.ssh/id_rsa
hdfs_dfs_namenode_datanode_registration_ip_hostname_check: ''