- name: install epel
  yum:
    name: epel-release
    state: present

- name: install yum-utils
  yum:
    name: yum-utils
    state: present

- name: install rpm
  yum:
    name: http://rpms.remirepo.net/enterprise/remi-release-7.rpm
    state: present

- name: install remi
  shell:
    cmd: yum-config-manager --enable remi -y

- name: install redis rhel
  yum:
    name: redis
    state: present